# Generated by Django 3.0.3 on 2020-02-10 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss_reader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_published',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
